repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-executables-have-shebangs
- repo: local
  hooks:
  - id: rustfmt
    name: format rust code
    entry: cargo fmt
    language: rust
    types: [rust]
    pass_filenames: false
